notifications:
  email: false

sudo: required
language: node_js
node_js:
  - '6.2'
  - '5.1'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_script:
  - npm run dpkg-install
